owner: rdp-studio
repo: upptime

sites:
  - name: RPKI CA
    url: https://rpca.launchpadx.top

  - name: RPKI Validator
    url: https://rpki.launchpadx.top

  - name: Server Monitor
    url: https://tz.launchpadx.top

  - name: Grafana
    url: https://grafana.launchpadx.top

status-website:
  cname: status.launchpadx.top
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: LaunchPad Upptime
  introTitle: "Monitoring LaunchPad Workshop's services."
  introMessage: Powered by Upptime. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
