owner: rdp-studio
repo: upptime

sites:
  - name: RPKI CA
    url: https://rpca.launchpadx.top

  - name: RPKI Validator
    url: https://rpki.launchpadx.top

  - name: Looking Glass
    url: https://lg.launchpadx.top

  - name: Server Monitor
    url: https://tz.launchpadx.top

  - name: Grafana
    url: https://grafana.launchpadx.top

  - name: Anycast Recursive DNS
    url: https://dns.launchpadx.top/dns-query
    expectedStatusCodes: [400]

  - name: Anycast Ad-blocking DNS
    url: https://adns.launchpadx.top/dns-query
    expectedStatusCodes: [400]

  - name: Anycast DNS64 Recursive DNS
    url: https://dns64.launchpadx.top/dns-query
    expectedStatusCodes: [400]

  - name: Anycast DNS64 Ad-blocking DNS
    url: https://adns64.launchpadx.top/dns-query
    expectedStatusCodes: [400]

status-website:
  cname: status.launchpadx.top
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: LaunchPad Upptime
  introTitle: "Monitoring LaunchPad Workshop's services."
  introMessage: Powered by Upptime. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
